project:
  type: book

book:
  title: "Longitudinal Data Modeling"
  author:
    - name: Dr. Marietta Kirchner
      affiliation: Institute of Medical Biometry, Heidelberg University
    - name: Dr. Alexandra Lauer
      affiliation: Boehringer Ingelheim Pharma GmbH & Co. KG
  date: "09/24/2024"
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - s1_visualization.qmd
    - s2_inference_continuous.qmd
    - s3_missingness.qmd
    - s4_sensitivity_analyses.qmd
    - s5_inferences_binary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

