# Preface {.unnumbered}

```{r}
#| echo: false
#| message: false
renv::install("tidyverse")
renv::install("mmrm")
renv::install("emmeans")

library(tidyverse)
library(mmrm)
library(emmeans)
```



```{r}
#| echo: false
df_wide <- data.frame(
  "subject" = 1:50,
  "treatment" = c(2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1,2, 1,2,1,1,2,2,2,2,1,1,2,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,1,2,1,2,2,1,1,2),
  "sex" = factor(
    c(1,1,1,2,1,1,1,1,1,1,1,1,2,1,1,2,1,1,2,1,1,2,1,2,1,1,2,2,1,1,1,2,2,2,1,2,1,1,2,2,2,2,2,1,2,2,1,2,2,1),
    labels = c("F", "M")
  ),
  "base" = c(24,20,18,10,12,14,17,21,19,19,20,19,20,19,19,19,20,23,26,19,24,19,20,20,22,23,21,21,20,19,13,24,18,21,20,20,20,22,20,18,20,15,19,8,20,20,35,17,23,18),
  "t1" = c(-11,-6,-1,-9,-6,-6,-7,-2,-9,-13,-11,-7,-9,-6,-12,-3,-9,-7,-5,0,-12,0,-7,1,0,-12,-1,-2,-3,-2,-1,-10,-4,-2,-5,-4,-3,-3,-6,-5,5,0,-3,-6,-9,-6,-8,-10,4,-1),
  "t2" = c(-16,-8,-1,-6,-3,-10,-7,-9,-6,-12,-15,-15,-12,-12,-15,-11,-13,-10,-5,-1,-15,-2,-8,-1,-4,-17,-2,-2,-8,-2,-4,-14,-10,-1,-10,-4,-6,-5,-9,-9,-2,-2,-9,-3,-11,-5,-14,-14,-4,-1),
  "t3" =c(-24,-5,-9,-9,-9,-10,-14,-9,-10,-14,-20,-19,-13,-16,-18,-17,-19,-15,-11,-8,-19,-10,-13,-6,-9,-22,-3,-2,-13,0,-11,-20,-15,-6,-15,-10,-12,-6,-13,-15,-10,-8,-11,-7,-9,-9,1,-14,-13,-9)
) %>% 
  tidyr::pivot_longer(cols = c("t1", "t2", "t3"), names_to = "avisit", values_to = "chg") %>% 
  dplyr::mutate(
    aval = base + chg
  )

base <- dplyr::distinct(df_wide, treatment, sex, subject, base) %>% 
  dplyr::mutate(
    aval = base,
    avisit = "baseline",
    chg = NA_real_
  )


df <- rbind(df_wide, base) %>% 
  dplyr::mutate(
    avisit = factor(avisit, levels = c("baseline", "t1", "t2", "t3"))
  ) %>% 
  dplyr::arrange(subject, avisit)
```

